llaske/sugarizer-server

api/controller/classrooms.js
api/controller/users.js
dashboard/controller/classrooms.js
dashboard/route.js
dashboard/views/addEditClassroom.ejs
dashboard/views/classrooms.ejs
dashboard/views/includes/sidebar.ejs
dashboard/views/users.ejs

whats remaining
1. Locales
2. change student ids in GET to classid and write query logic at API level
3. student Add/Del module in classroom
4. testing
5. classroom icons (Needed from Lionel)

basic  features of dashboard added

---

dashboard/controller/users.js

This will allow to create users with spaces in their name

create new user with space in name

---

.gitignore
dashboard/controller/dashboard.js
dashboard/views/dashboard.ejs

Added classroom counter to dashboard home

---

dashboard/controller/activities/fakeLaunch.js
dashboard/controller/activities/index.js
dashboard/controller/activities/launch.js
dashboard/controller/activities/util/index.js

The dev branch is broken after PR #34 
There are multiple issues including importing files from incorrect path. Use of ES6 syntax (Import statement, destructuring, etc.).
Since it won't be possible for anyone to work on dev branch, @tarunsinghal92 I'm goind ahead and making this PR though it was assigned to @imdhruvgupta to fix these issues.
Closes #49

[FIX] Fixes breaking changes

---

dashboard/controller/auth.js

[FIX] Server crash fix

---

dashboard/controller/classrooms.js
dashboard/controller/users.js

Earlier the add user and classroom routes were not working because `server` variable was not passed in `res.render` call .

Crash fix #69 

---

dashboard/controller/classrooms.js

Fixed #56 
Student count increased

Classroom and User page crash #56 fixed

---

dashboard/controller/classrooms.js
dashboard/controller/users.js
dashboard/public/l10n/locales.ini
dashboard/views/classrooms.ejs

Some translations were previously missing. I've added those translations.
Also fixed an error related to passing arguments in file `dashboard/views/classrooms.ejs`

Added missing translations

---

dashboard/views/classrooms.ejs
dashboard/views/users.ejs

Fix issue created by PR #73.
After adding one classroom/user, if you click on `Add Classroom`/`Add User` button again. It shows error 404.
(It was due to relative routing wrt current route)

Fix add another classroom/user issue

---

dashboard/controller/graph.js
dashboard/public/js/main.js

Fixes #84
Go to the User journal page OR Launch activity page when admin clicks on the chart.
**Top Contributors chart:**
**Top Activities chart:**

Go to User journal / Launch activity when clicked on chart

---

dashboard/views/journal.ejs

Earlier wrong field was used for showing size in journal view as mentioned by @llaske [here](https://github.com/llaske/sugarizer-server/pull/67#issuecomment-472199663)

size column in journal view

---

api/controller/users.js
api/test/classrooms.js

The student count of a classroom is not updated when we delete a user.
API Test:

Classroom user count fix

---

dashboard/public/l10n/locales.ini
dashboard/views/journal.ejs

localized strings as mentioned by @llaske in #94

localisation added in size column

---

dashboard/controller/stats.js
dashboard/public/l10n/locales.ini

- Translated stats labels which were not previously translated.
- Corrected and added some translations.

Updated translations

---

api/controller/activities.js

Fixes #139 
Following issue #139, I've identified and fixed potential global vars in API which can cause inconsistency during parallel function calls.

Fix API inconsistency for asynchronous calls

---

dashboard/views/journal.ejs

This pr fixes issue created in #124 as mentioned in #131

#131 fixed 

---

dashboard/public/css/material-dashboard.css
dashboard/public/js/main.js
dashboard/views/includes/navbar.ejs

Fixes #154 
Language toggle was not working in the mobile view.
Issue:
P.S. My screen recorder is not displaying the language list.
Fixed:

Initiate language change on sidebar toggle

---

api/controller/users.js
api/test/users.js

Fixes #109 
Delete private journal on delete user
Tests passed:
I've checked the journals collection. It's not storing extra data after test completion. (Previously it was storing private journals unnecessarily) 
I had to modify the test for users. It was deleting journal after deleting the user. But since the journal is deleted with the user, the test was failing so I had to make appropriate changes.

Delete private journal on delete user

---

api/controller/classrooms.js
api/controller/journal.js
api/controller/stats.js
api/controller/users.js
api/route.js
config/wait4db.js
sugarizer.js

`client.connect` was not handled in the `api/controller`. If the database is not running, the application should exit with an error code and return that application cannot be connected with DB.

Use single instance of db connection

---

dashboard/public/l10n/locales.ini
dashboard/views/activities.ejs

In the Activities view, the drag icon and toggle-favorite icon were missing the tooltips.

UX Improvement. Added tool-tips for icons

---

dashboard/views/users.ejs

Translation for Language of users was added in #145 But looks like it is not working now 
Current : 
Expected :

Translations for user language

---

dashboard/views/addEditClassroom.ejs
dashboard/views/addEditUser.ejs

Use a random color for new user/classroom created from dashboard

---

.gitignore
package.json
scripts/seed_users.js

Run `npm run seed:users-csv -- filename.csv` to seed data from CSV.

Script to import Users from CSV

---

dashboard/controller/stats.js

Change the assignment of  0 with 1 when we add it for the 1st time to object #119 #120

Fix chart not showing any data for single entry

---

dashboard/controller/auth/getLogin.js
dashboard/controller/auth/index.js
dashboard/controller/auth/logout.js
dashboard/controller/auth/postLogin.js
dashboard/controller/auth/validateSession.js

[REFACTOR] Restructured auth controller

---

dashboard/controller/stats/getGraph.js
dashboard/controller/stats/index.js
dashboard/controller/stats/util/index.js

[REFACTOR] Restructured stats controller

---

dashboard/controller/dashboard/index.js
dashboard/controller/dashboard/util/index.js
dashboard/controller/graph.js

[REFACTOR] Restructured dashboard controller

---

dashboard/controller/classrooms/addClassroom.js

Update dashboard reference in addClassroom

---

.eslintignore
.eslintrc.json
package.json

@llaske @tarunsinghal92 I have written the configuration for eslint. I've tried to minimize the errors.
Currently, it's detecting 278 errors. Out of which 9 can be automatically fixed. Should I go ahead and fix those errors manually?
Also, I need suggestions for linting `.ejs` files. I could not find any good plugin for linting them.

Installing linter in the project

---

.gitignore
Gruntfile.js
README.md
package.json

Grunt to minify public JS resources

Grunt to minify public resources

---

api/controller/users.js
dashboard/controller/users/addUser.js
dashboard/controller/users/editUser.js
dashboard/views/addEditUser.ejs

Prevents the admin from changing user roles.

Disable user role change

---

dashboard/controller/users/exportCSV.js
dashboard/controller/users/importCSV.js
dashboard/public/js/main.js
dashboard/views/users.ejs

In continuation with PR #189. Just realized that I forgot to push the last commit

Stroke and fill in imp/exp

---

api/controller/journal.js
dashboard/public/css/main.css
dashboard/public/js/main.js
dashboard/views/journal.ejs

Sort journal by title

---

api/controller/charts.js
dashboard/controller/stats/getGraph.js
dashboard/controller/stats/util/chartList.js
dashboard/controller/stats/util/index.js
dashboard/public/l10n/locales.ini

- Top classrooms by student count (Bar)
- Most active classrooms by student entries (Bar)

New charts added

---

README.md

I have corrected a few typos and made some grammatical corrections

docs: Made some minor corrections

---

package-lock.json
package.json

Nodemon should be installed as a dev-dependency. Generated `package-lock.json` accordingly.

Nodemon as dev-dependency

---

api/controller/journal.js

Fixes #208
@llaske can you please test this patch.

Remove text field from aggregate journal query

---

api/controller/classrooms.js
api/test/classrooms.js
dashboard/controller/classrooms/addClassroom.js
dashboard/views/admin/addEditClassroom.ejs

_AddEditClassroom_ View was slowing down for large number of users in the database.
Removed [multiselect.js](http://loudev.com) and replaced it with [jQuery Select2](https://select2.github.io/select2).
Select2 makes AJAX queries for searching on the backend instead of searching on the client-side.
@llaske can you please test this PR before merging.

Classroom user search

---

api/controller/auth.js
api/controller/users.js
dashboard/public/js/main.js
dashboard/views/users.ejs

This patch allows the teacher to log in to Sugarizer.
Fixes #222

Allow teacher login on Sugarizer

---

dashboard/controller/graph/util/index.js

Correct icons in recent entries table

---

dashboard/controller/activities/launch.js
dashboard/controller/activities/util/index.js
dashboard/controller/journal/deleteEntry.js
dashboard/controller/journal/getEntries.js
dashboard/controller/journal/index.js
dashboard/public/css/main.css
dashboard/public/js/main.js
dashboard/public/l10n/locales.ini
dashboard/views/journal.ejs

Journal Upload

---

dashboard/public/css/main.css

[Issue #238 fix] Fixed dropbox overflow

---

dashboard/views/users.ejs

[Issue #240 fix] Fixed selected text localization

---

dashboard/views/admin/addEditClassroom.ejs

The preload-data line is causing an error in the console and is not required.

Removed select2 data preload

---

dashboard/controller/classrooms/index.js
dashboard/public/js/main.js
dashboard/public/l10n/locales.ini
dashboard/views/classrooms.ejs

Added multi-delete feature in the classroom view (following #249)

Added multi-delete in classroom view

---

api/controller/auth.js
docs/www/api_data.js
docs/www/api_data.json

Fixes llaske/sugarizer#580.
This PR is analogous to llaske/sugarizer#786. Handles the new `beforeSignup` flag and adds `validateUsername` function similar to `validateUser` to check for the uniqueness of username.

Updated signup function to validate name

---

README.md
config/wait4db.js
docker/Dockerfile-standalone
env/docker.ini
env/sugarizer.ini
env/test.ini

This commit contains the changes required to integrate Sugarizer Server with Sugarizer School Portal.
- Changes in the connection string to allow connection with mongodb replicaset.
- Dockerfile to generate Sugarizer Server image which will be used by [Sugarizer Chart](https://github.com/NikhilM98/sugarizer-chart) to create a container.

Configuration changes for Sugarizer School Portal
