llaske/sugarizer-server

- dashboard/controller/classrooms.js
- dashboard/controller/users.js
- dashboard/views/classrooms.ejs
- dashboard/views/users.ejs
While creating/editing user/classroom, when the user clicks on add user. Page reloads and a success popup appears. I think the user should be redirected to the dashboard/users or dashboard/classroom views after the successful creation of a user/classroom. Current UX is a little confusing. The user can click on create user button multiple times.
Current behavior:
Expected behavior:
> UX improvement

- dashboard/public/js/main.js
While sorting the activities, the numbering of the activities appears ambiguous on picking up the element.
On dragging an item, it appears as if there is a vacancy of two elements instead of one.
Solution: The wrong ordering is due to the hidden `<li>` placeholder element. I used `<div>` for the placeholder instead so it's not causing ambiguities in the ordering of the list.
> Fix the ordering of activities while sorting

- api/controller/users.js
- dashboard/controller/users.js
The tests were failing after PR #83 
Moved the logic to check that if the admin is deleting himself to `dashboard/controller`
Failing tests:
After fix:
The functionality introduced by #83 is also handled and is working as expected.
> Fixes breaking tests. Handling admin deletion 

- dashboard/controller/stats.js
Fixes #95 
- All users were active during last month:
- Three users were active and two users weren't:
> Fix Statistics page showing all users as inactive

- dashboard/controller/classrooms.js
When I add a classroom with a single student, a string is stored in the DB instead of an array.
Steps to reproduce the  error:
1. Login to the dashboard. Click on `Classrooms` tab.
2. Click on `ADD CLASSROOM` button and create a classroom with one student.
3. If you check the database, you'll find a string insted of an array in the classrooms collection. If you list the classrooms, count for that classroom will be incorrect and `view students` button will be disabled.
(See the last classroom. Student count is incorrect and we view students button is disabled.)
P.S. Also removed a function defined inside a function. The scope of the function was incorrect and it was unnecessary.
> [FIX] Creating classroom with single student

- dashboard/controller/users.js
- dashboard/views/users.ejs
I was facing this issue while testing PR #101.
After creating/editing/deleting an admin, the app returns me to users view listing students instead of admins. It's really frustrating to delete/edit multiple admins and It's difficult to keep track of your last action.
Current behavior:
Expected behavior:
(When user creates/updates/deletes admin, he gets the list of admins)
> UX Improvement. List admins after create/update/delete admin

- dashboard/public/js/main.js
The search for stroke and fill color was not working while creating user/classroom.
> Search for stroke and fill fixed

- api/controller/classrooms.js
- api/controller/journal.js
- api/controller/stats.js
- api/controller/users.js
- api/test/activities.js
- api/test/classrooms.js
- api/test/journal.js
- api/test/stats.js
- api/test/users.js
- Some of the MongoDB functions were deprecated. They have been updated with a suitable alternative.
- In the tests, while creating fake admin, the language parameter is passed to admin which was previously missing.
- Following [chaijs docs](https://www.chaijs.com/api/bdd/) I updated `be.a('array')` and `be.a('object')` with `be.an('array')` and `be.an('object')` respectively.
> Updated deprecated mongodb functions

- dashboard/public/js/main.js
Fixes #130 
Currently, when we try to launch an activity with null journal entry text from the dashboard. The activity fails to launch and we get an error in the console:
It was fixed by adding a simple null check in the `launch_activity` function.
> Fix launching activity with null text

- dashboard/public/js/main.js
Steps to reproduce the error:
1. Open dashboard. Navigate to statistics page.
2. Keep the developer console open and click on "How often users are changing their profile settings?" chart.
You'll get an error like this:
Cause of error: In PR #85 an event listener was added to all the charts. It should be added to only a couple of charts. The error was popping because of the event listener being attached to the wrong chart and the function breaking down because of undefined variables.
In this PR:
- Instead of attaching the event listener to all the charts. It's attached to only selected charts thus eliminating the error and the improving efficiency.
- ES6 template literals were removed due to lack of support in the older browsers version.
> Fix console error on bar chart onClick

- dashboard/views/journal.ejs
When the user selects Shared Journal and clicks on Show Results, the select field shows Private Journal as selected.
> Fix incorrect value in journal select field

- dashboard/controller/graph.js
- dashboard/views/dashboard.ejs
**Current state:**
The admin doesn't know to whom any of these activities belong. 
Currently the admin can launch a specific instance of an activity by clicking on it in the table, but since he doesn't know the owner of any of these activities, he/she can't tell who made this progress in the activity which makes the point of launching it from the table useless.
---
**After PR:**
> Add username in the "Recent Entries" table

- dashboard/controller/users.js
As seen in the below GIF, when the admin creates a new user, if there's a data validation error in the _Name_ or _Password_ field, **all the entered data is cleared** when the alerts pop up.
---
**Fix:** Remember all the filled in data (Name, Language, Role, Color, Password) after alerts pops up.
> Remember filled in new user data when there's a data validation error

- dashboard/views/addEditClassroom.ejs
The placeholder in the addEditClassroom view for `Search Students` field was not being translated due to a typo and we were also getting warnings in the console.
Fixed:
> Fixed placeholder translation in addEditClassroom

- dashboard/public/css/main.css
- dashboard/public/js/main.js
- dashboard/views/dashboard.ejs
- dashboard/views/includes/sidebar.ejs
Following the discussion on PR #43 
- Server translations are reloaded on locale change.
- Links on the dashboard were missing locale parameter.
- The cursor on the sidebar links was not appearing as a pointer.
> Dropdown language change fix

- dashboard/controller/stats.js
The l10n instance was not initiated on the stats controller.
If a user switched language and moved to stats page, the language of the graphs was not changed.
> Re-init l10n in stats controller

- dashboard/views/users.ejs
In general case, there seems no point of showing view journal button for admin and teachers on the users view. It should be displayed only for the student accounts.
Student:
Admin/Teacher:
> Show view journal button only for students in users view

- dashboard/controller/users.js
- dashboard/views/users.ejs
While using filters in the `Users View`. If Class A and Class B have the same students. If we use the filter for Class B, then it displays the name of Class B in the select field.
Fixed:
> Fix classroom for similar students

- dashboard/public/css/main.css
- dashboard/views/activities.ejs
- dashboard/views/includes/navbar.ejs
- In the activities view, since reordering by clicking anywhere on the row to drag feature is replaced with dragging the row by clicking on the vertical ellipsis, we need to make the cursor pointer when the user hovers on the icon such that he can know that there's an action associated with that icon.
- On the navbar, the name of the pages is a clickable link.
They're replaced with divs in this PR.
- The XO icons in some pages have cursor pointer associated with them. It makes the user think that they're buttons instead of images.
Fixed:
> UX improvement. Fixed links and cursor

- dashboard/controller/classrooms.js
- dashboard/controller/dashboard.js
- dashboard/controller/journal.js
- dashboard/controller/stats.js
- dashboard/controller/users.js
- dashboard/helper/common.js
Currently, the locale is re-initiated only on view's index page.
- This causes issues with switching locale on non-index views like:
- This causes an issue with the translation of notifications
This PR contains:
- Translation fix on non-index views:
- Translation fix for notifications:
> Re-initiated locale on non-index views

- dashboard/public/css/main.css
- dashboard/public/css/material-dashboard.css
- dashboard/views/dashboard.ejs
This PR contains:
- The sidebar is not scrollable on mobile devices.
-> Enabled scroll on mobile view.
- Tables on the dashboard home page were not responsive. The text was going out of the table.
-> Made the table responsive.
Current:
Fix:
> Improve responsive view

- dashboard/views/classrooms.ejs
When navigating from Classroom view to Users view by clicking on `ViewStudents` button, the name of the Classroom is not displayed in the Classroom-Select field.
Current Behaviour:
> Fix classroom name on view students from classroom view

- dashboard/public/css/material-dashboard.css
- dashboard/views/login.ejs
In the mobile view, the navbar position is relative.
If a user scrolls to the bottom of the page and he wants to navigate to another view then he has to scroll back to the top of the page to access the sidebar.
Patch:
> Improve navigation on mobile view

- dashboard/public/js/main.js
When the language is changed, the page is being translated redundantly on the front end:
1. When the language is changed, the front-end is triggered to translate the language.
2. When the page reloads, it is again translated.
Current behavior:
Patch:
Removed the `l10n` call to update the language on drop-down option change.
> Removed redundant translation on language change

- package-lock.json
- package.json
`npm audit` report on dev branch:
`npm audit` report after patch:
npm version: 6.5.0-next.0
node version: v11.6.0
Updated `grunt` and `grunt-contrib-uglify` versions. Public resource minification seems to work fine after the update. Also updated `lodash` in `package-lock.json`.
> Package vulnerability fix

- .eslintignore
- .eslintrc.json
- api/controller/journal.js
Excluded `qrcodegen.js` library from the eslint check.
> Updated eslint config

- api/controller/classrooms.js
- api/controller/journal.js
- api/controller/users.js
- dashboard/controller/activities/util/index.js
- dashboard/controller/stats/util/index.js
- dashboard/public/js/main.js
ESLint restricts the use of [Object.prototypes builtins directly](https://eslint.org/docs/rules/no-prototype-builtins).
On running `npm run lint`:
Running tests after fixing the issue:
> no-prototype-builtins error removed

- dashboard/public/js/main.js
Fixes #142.
On localization, I'm taking the current query and modifying it to update the language. I handled all three cases:
1. Query string empty (appending the lang)
2. Query non-empty but does not contain lang parameter (adding lang)
3. Query non-empty and contains lang parameter (Updating lang using regex)
@NikhilM98 I believe this solution would not have any unexpected results as it's basically similar to refreshing the page, which was already taking place in case of language switching. The other query parameters stay the same regardless of the language chosen, hence not impacting the query search.
Please review @llaske, @NikhilM98 and @ashish0910.
> [Issue #142 fix] Fixed query retention after language switch

- dashboard/public/js/main.js
In the Journal view, the tutorial starts from step 3 when we try to restart the tutorial.
Expected behaviour:
Current behaviour:
> Start tutorial from beginning in journal view

- docs/deploytoGCP.md
Documentation fixes
Paste was spelled wrong and the commands to be pasted were missing.
Some commands and steps are different for GCP so they need to be defined here for easy deployment.
> Documentation fixes for deploying to GCP

- dashboard/controller/activities/index.js
- dashboard/controller/activities/launch.js
- dashboard/controller/activities/util/index.js
- dashboard/controller/auth/postLogin.js
- dashboard/controller/classrooms/addClassroom.js
- dashboard/controller/classrooms/deleteClassroom.js
- dashboard/controller/classrooms/editClassroom.js
- dashboard/controller/classrooms/index.js
- dashboard/controller/dashboard/util/index.js
- dashboard/controller/graph/util/index.js
- dashboard/controller/journal/deleteEntry.js
- dashboard/controller/journal/util/index.js
- dashboard/controller/stats/addChart.js
- dashboard/controller/stats/deleteChart.js
- dashboard/controller/stats/editChart.js
- dashboard/controller/stats/index.js
- dashboard/controller/stats/listCharts.js
- dashboard/controller/stats/util/index.js
- dashboard/controller/users/addUser.js
- dashboard/controller/users/deleteUser.js
- dashboard/controller/users/editUser.js
- dashboard/controller/users/exportCSV.js
- dashboard/controller/users/importCSV.js
- dashboard/controller/users/index.js
- dashboard/controller/users/profile.js
- dashboard/controller/users/searchUser.js
- dashboard/controller/users/util/index.js
- package-lock.json
- package.json
- scripts/seed_users.js
Fixes #254
Replacing `Request` with `Superagent`.
Commit [14dd7](https://github.com/llaske/sugarizer-server/commit/14dd7cb01e282ea2baee1842b7cea8e9c68381e7) shows the modification we need to do to replace `request` with `superagent` in each file.
The changes are minimal.
- Both libraries use a callback function.
- HTTP Request Method, Headers and Query String can be set easily and the inside logic remains the same.
- Just have to replace `body` with `request.body` inside the function.
@llaske Should we go ahead with `Superagent` and remove `request` dependence completely?
> Replace request with superagent

- dashboard/views/activities.ejs
- dashboard/views/admin/listCharts.ejs
- dashboard/views/admin/stats.ejs
- dashboard/views/dashboard.ejs
`flash-errors` was not included in some views where server popup is used due to which server popup is not displayed.
Steps to reproduce: When you try to Add/Edit/Delete a Chart, server popup will not be displayed.
Popup is displayed after applying the patch:
> Fix server error flashing

- dashboard/controller/classrooms/addClassroom.js
- dashboard/controller/classrooms/editClassroom.js
- dashboard/controller/stats/addChart.js
- dashboard/controller/stats/editChart.js
- dashboard/public/js/tutorial.js
- dashboard/views/addEditUser.ejs
- dashboard/views/admin/addEditChart.ejs
- dashboard/views/admin/addEditClassroom.ejs
This PR fixes two issues:
First issue:
The tutorial for a view is supposed to run only one time when the user opens the view. If the user wants to view the tutorial again, they can click on the help button.
The tutorial for AddEditUser, AddEditClassroom and AddEditChart view keeps restarting without pressing the help button.
Steps to reproduce:
1. Clear Local Storage.
2. Open Add Classroom view. The tutorial runs automatically for the Add Classroom view.
3. Open Edit Classroom view. The tutorial runs automatically for the Edit Classroom view.
4. Open Add Classroom view again. The tutorial runs automatically for the Add Classroom view again. It is not supposed to run again automatically.
[42c098](https://github.com/llaske/sugarizer-server/commit/42c0987a8ac70a7c257523d668b8d139699ef333) …
> Fix tutorial restart

- docs/install.md
Fixed #276 
Updated docker compose install command as given [here](https://docs.docker.com/compose/install/):
```
curl -L "https://github.com/docker/compose/releases/download/1.8.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```
> Fixed Permission error in install.md

- dashboard/public/css/main.css
A same css change on the language selector
> Issue fix #294: text align changed on Language selector

- dashboard/public/css/main.css
- dashboard/public/css/material-dashboard.css
Fix for the issue #348 
Changes I have made :- 
- Made the user dropdown for profile feature and logout feature "hidden" once the width is less than 992px.
- Made the logout button visible once it is under the width of 992px. (earlier it was only for less than 768px)
- Removed box shadow from language selector for much more cleaner look (because it was only there when the width was less than 768px and not 992px).
- Also reduced some margin between logout button and language selector for better experience.
Below I have attached a video of how it looks now.
https://user-images.githubusercontent.com/54149585/218292935-86fb2385-6ad9-4bfe-a4af-ee0d5ef856e7.mov
> fixed sidebar logout option
